apiVersion: v1
kind: Secret
metadata:
  name: hermes-secrets
  namespace: hermes-namespace
type: Opaque
stringData:
  POSTGRES_USER: hermes
  POSTGRES_PASSWORD: hermes
  POSTGRES_DB: hermes
  JWT_SECRET: "dGhpcy1pcy1hLXN0cm9uZy1zZWNyZXQtZm9yLWhlcm1lcy1kZXY="
