apiVersion: v1
kind: Service
metadata:
  name: hermes-cassandra
  namespace: hermes-namespace
spec:
  selector:
    app: hermes-cassandra
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
