apiVersion: v1
kind: Service
metadata:
  name: hermes-postgres
  namespace: hermes-namespace
spec:
  selector:
    app: hermes-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
