apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-statefulset
  namespace: hermes-namespace
spec:
  serviceName: hermes-cassandra
  replicas: 1
  selector:
    matchLabels:
      app: hermes-cassandra
  template:
    metadata:
      labels:
        app: hermes-cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "HermesCluster"
            - name: CASSANDRA_DC
              value: "datacenter1"
          startupProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 12
          readinessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 10
            periodSeconds: 15
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
